fix 4

diff --git a/.github/workflows/docker-deployment.yml b/.github/workflows/docker-deployment.yml
--- a/.github/workflows/docker-deployment.yml
+++ b/.github/workflows/docker-deployment.yml
@@ -37,8 +37,8 @@ jobs:
         run: sudo apt-get update && sudo apt-get install docker-compose -y
 
       - name: Start services with Docker Compose
-        run: docker-compose up -d -f docker-compose-dev.yml --build
+        run: docker-compose up -d --build
 
       - name: Run migrations
         run: |
-          docker-compose -f docker-compose-dev.yml exec -T django python manage.py migrate || { echo 'Migrations failed'; exit 1; }
+          docker-compose exec -T django python manage.py migrate || { echo 'Migrations failed'; exit 1; }
